services:
  powerdev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BLENDER_DOWNLOAD_URL=https://mirror.clarkson.edu/blender/release/Blender4.5/blender-4.5.0-linux-x64.tar.xz
    image: powerdev:latest
    container_name: powerdev

    # GPU support (uncomment if you have NVIDIA GPU)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - DISPLAY=:99
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTHONUNBUFFERED=1

    ports:
      - "9876:9876"    # Blender MCP server (for local Blender if needed)
      - "3000:3000"    # Claude Flow UI
      - "3002:3002"    # Claude Flow MCP Server
      - "3005:3005"    # Additional services
      - "8080:8080"    # Web services
      - "5173:5173"    # Vite dev server

    volumes:
      - ./workspace:/workspace
      - ./blender-files:/blender-files
      - ./pbr_outputs:/workspace/pbr_outputs
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${EXTERNAL_DIR:-./.agent-mount/ext}:/workspace/ext

    # Run in interactive mode by default
    command: ["--interactive"]

    # Keep stdin open and allocate a pseudo-TTY
    stdin_open: true
    tty: true

    # Security options
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE

    # Resource limits
    mem_limit: ${DOCKER_MEMORY:-16g}
    cpus: "${DOCKER_CPUS:-4}"

    # Healthcheck
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

    # Restart policy
    restart: unless-stopped

    networks:
      - docker_ragflow
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "blender-host:192.168.0.216"  # Direct mapping for Blender MCP server

  # Optional: Claude Flow standalone service
  claude-flow:
    image: powerdev:latest
    container_name: claude-flow-ui
    command: ["claude-flow", "start", "--ui", "--port", "3000"]
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
    networks:
      - docker_ragflow
    profiles:
      - standalone

  # Rust container that connects to the powerdev MCP
  logseq_spring_thing_webxr:
    image: rust:latest # Replace with your actual Rust image
    container_name: logseq_spring_thing_webxr
    environment:
      - CLAUDE_FLOW_HOST=powerdev
      - CLAUDE_FLOW_PORT=3000
      - RUST_LOG=info
    depends_on:
      powerdev:
        condition: service_healthy
    networks:
      - docker_ragflow
    restart: unless-stopped

networks:
  docker_ragflow:
    external: true

volumes:
  workspace:
  blender-files: