services:
  multi-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: multi-agent-docker:latest
    container_name: multi-agent-container

    # GPU support (uncomment if you have NVIDIA GPU)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - DISPLAY=:99
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTHONUNBUFFERED=1
      - BLENDER_HOST=gui-tools-service
      - BLENDER_PORT=9876
      - QGIS_HOST=gui-tools-service
      - QGIS_PORT=9877
      - PBR_HOST=gui-tools-service
      - PBR_PORT=9878

    ports:
      - "3000:3000"    # Claude Flow UI
      - "3002:3002"    # Claude Flow MCP WebSocket Bridge

    volumes:
      - ./workspace:/workspace
      - ./blender-files:/blender-files
      - ./pbr_outputs:/workspace/pbr_outputs
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${EXTERNAL_DIR:-./.agent-mount/ext}:/workspace/ext

    # Run in interactive mode by default
    command: ["--interactive"]

    # Keep stdin open and allocate a pseudo-TTY
    stdin_open: true
    tty: true

    # Security options
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE

    # Resource limits
    mem_limit: ${DOCKER_MEMORY:-16g}
    cpus: "${DOCKER_CPUS:-4}"

    # Healthcheck
    healthcheck:
      test: ["CMD", "sh", "-c", "command -v claude-flow >/dev/null"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

    # Restart policy
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  workspace:
  blender-files: