version: '3.8'

services:
  blender-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BLENDER_DOWNLOAD_URL=https://mirror.clarkson.edu/blender/release/Blender4.5/blender-4.5.0-linux-x64.tar.xz
    image: blender-mcp-dev:latest
    container_name: blender-mcp-container
    
    # GPU support (uncomment if you have NVIDIA GPU)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    
    environment:
      - DISPLAY=:99
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTHONUNBUFFERED=1
      
    ports:
      - "9876:9876"    # Blender MCP server
      - "3000:3000"    # Claude Flow UI
      - "3001:3001"    # Additional services
      
    volumes:
      - ./workspace:/workspace
      - ./blender-files:/blender-files
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      
    # Run in interactive mode by default
    command: ["--interactive"]
    
    # Keep stdin open and allocate a pseudo-TTY
    stdin_open: true
    tty: true
    
    # Security options
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfirmed
    cap_add:
      - SYS_PTRACE
      
    # Resource limits
    mem_limit: 8g
    cpus: "4.0"
    
    # Healthcheck
    healthcheck:
      test: ["CMD", "pgrep", "-f", "blender"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
      
    # Restart policy
    restart: unless-stopped
    
    networks:
      - blender-net

  # Optional: Claude Flow standalone service
  claude-flow:
    image: blender-mcp-dev:latest
    container_name: claude-flow-ui
    command: ["claude-flow", "start", "--ui", "--port", "3000"]
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
    networks:
      - blender-net
    profiles:
      - standalone

networks:
  blender-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  workspace:
  blender-files: