#!/bin/sh
# This script is sourced by /etc/bash.bashrc to display a welcome message.

echo ""
echo "--- 🚀 Welcome to the Multi-Agent Docker Environment ---"
echo ""
echo "To complete your one-time setup, please run the following commands in order:"
echo ""
echo "1. claude --dangerously-skip-permissions"
echo ""
echo "sudo chown dev:dev .mcp.json"
echo ""
echo "2. Run the environment enhancement script:"
echo "   /app/setup-workspace.sh"
echo ""
echo "3. Reload your shell to activate all aliases and settings:"
echo "   source /home/dev/.bashrc"
echo ""
echo "This message will disappear after you run the setup script."
echo "--------------------------------------------------------"
echo ""